name: 02 Sonar Analysis

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  sonar-backend:
    name: Sonar Backend (Java)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: dsw01_practica02
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Run backend tests
        working-directory: backend
        run: mvn clean test

      - name: Sonar Backend Scan
        working-directory: backend
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=Ariadna-19_DSW01-Practica02 \
            -Dsonar.organization=ariadna-19 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src/main/java \
            -Dsonar.tests=src/test/java \
            -Dsonar.java.binaries=target/classes


  sonar-frontend:
    name: Sonar Frontend (Angular FIXED)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Run Angular tests (headless FIXED)
        working-directory: frontend
        run: |
          npm run test -- \
            --watch=false \
            --code-coverage \
            --browsers=ChromeHeadless

      - name: Verify coverage exists
        working-directory: frontend
        run: ls -la coverage || echo "NO coverage generated"

      - name: Sonar Frontend Scan
        working-directory: frontend
        run: |
          npx sonar-scanner \
            -Dsonar.projectKey=Ariadna-19_DSW01-Practica02-frontend \
            -Dsonar.organization=ariadna-19 \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src \
            -Dsonar.tests=src \
            -Dsonar.test.inclusions=**/*.spec.ts \
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info \
            -Dsonar.exclusions=node_modules/**,dist/**,.angular/**
